"""Dump BattleGrid's raw discovery responses, for `generate_mcp_reference.py`.

The gap this closes: CLAUDE.md says one tool regenerates both the surface record
and the reference, and two do. `probe_mcp_surface.py` writes the record;
`generate_mcp_reference.py` reads a *directory of raw JSON-RPC dumps* that
nothing in the repository produced. So the reference could only ever be
regenerated by whoever had those files, and it sat at v17.2.0 while the record
moved to v18.2.0 (#186).

This is the missing step, and deliberately nothing more. It captures and writes;
it does not interpret. The five discovery files are the server's own envelopes,
unedited, because the generator reads `["result"]` out of each and any shaping
here would be this tool deciding what the reference is allowed to say.

The two body files are the only ones with a wrapper, and it is an index rather
than an edit: one `{"entries": [...]}` list holding, per entry, its identity
plus the server's own `result` — or the refusal, verbatim, under `failure`.
A file cannot hold five envelopes without saying which is which.

The other two are the **prose bodies** —
`prompts/get` per listed prompt, `resources/read` per listed resource — which
the lists could only name: the `author-strategy` prompt alone is ~5,900
characters of binding authoring sequence that existed nowhere in this
repository until #294.

The protocol handling is imported from the probe rather than repeated. Two
implementations of "speak MCP and unwrap an SSE frame" would drift, and the
probe's is the one that has been run against a live server through six major
versions.

    BATTLEGRID_API_KEY=bg_live_… python3 tools/capture_mcp_dump.py build_log/dump
    python3 tools/generate_mcp_reference.py build_log/dump
    cp build_log/dump/mcp-capabilities.json docs/battlegrid-mcp-capabilities.json
    cp build_log/dump/mcp-reference.md      docs/BATTLEGRID_MCP_REFERENCE.md

Reconnaissance only. Every call is a discovery method — `initialize`, a list, or
a `prompts/get` / `resources/read` fetch of platform-authored prose. **No tool is
invoked**, so nothing here can write to an account.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from probe_mcp_surface import rpc  # noqa: E402

# What the generator opens, and the method that fills each. Kept as data so the
# two stay visibly paired — a file the generator reads and nothing writes is the
# defect this exists to fix, and the next one would look identical.
DUMPS: list[tuple[str, str, dict]] = [
    (
        "init.txt",
        "initialize",
        {
            "protocolVersion": "2025-06-18",
            "capabilities": {},
            "clientInfo": {"name": "grid-commander-capture", "version": "1.0.0"},
        },
    ),
    ("tools.json", "tools/list", {}),
    ("prompts.json", "prompts/list", {}),
    ("resources.json", "resources/list", {}),
    ("restemplates.json", "resources/templates/list", {}),
]


def harvest_bodies(key: str, out: Path) -> int:
    """Fetch every listed prompt's body and every listed resource's content.

    The lists alone record that a surface exists while losing what it binds —
    the `author-strategy` prompt was ~5,900 chars of authoring sequence with
    no copy in the repository (#294). Same posture as the list dumps: capture,
    do not interpret. Each entry carries the server's own `result`, or, when
    the server refuses, the refusal as a **named failure on that entry** —
    never absence, because an absent body and a never-fetched body are
    different facts and only one of them is a finding. One refusal does not
    abort the others.

    **Resource templates are listed and not fetched, deliberately.** A template
    is a URI pattern with holes; reading one means inventing values for those
    holes, and a body fetched under invented arguments is not the platform's
    prose — it is this tool's guess wearing the platform's voice. The server
    declares none today. If it ever declares one, it will appear in
    `restemplates.json` and have no body here, which is the honest state.

    Prompt argument *values* are deliberately not synthesised — every declared
    argument is optional, so the bodies come back in their unparameterised
    form. The empty `arguments: {}` is not a value, it is the envelope: all
    five prompts refuse `-32602 invalid_type ... received undefined` when the
    key is absent entirely (observed 2026-08-15 at v19.1.0, by this function's
    own named-failure path on its first run). Optional arguments, mandatory
    container.
    """
    failures = 0
    for out_name, method, listed, ident in (
        ("promptbodies.json", "prompts/get",
         [{"params": {"name": p["name"], "arguments": {}}, "id": {"name": p["name"]}}
          for p in json.loads((out / "prompts.json").read_text(encoding="utf-8"))["result"]["prompts"]],
         "name"),
        ("resourcebodies.json", "resources/read",
         [{"params": {"uri": r["uri"]}, "id": {"uri": r["uri"]}}
          for r in json.loads((out / "resources.json").read_text(encoding="utf-8"))["result"]["resources"]],
         "uri"),
    ):
        entries = []
        for item in listed:
            # Two ways a body fails to arrive, and both are the same fact here.
            # `rpc` retries transport errors and then *raises* — and
            # `urllib.error.HTTPError` is an `OSError`, so a 429 or a 500
            # arrives as an exception rather than as an error envelope. Left
            # uncaught it would abort the whole harvest and lose the entries
            # already fetched, which is precisely what this function promises
            # not to do.
            try:
                response = rpc(key, method, item["params"])
            except Exception as exc:  # noqa: BLE001 — any failure is a recorded fact
                response = {"error": {"transport": f"{type(exc).__name__}: {exc}"}}
            if "result" in response:
                entries.append({**item["id"], "result": response["result"]})
                note = ""
            else:
                failures += 1
                entries.append({**item["id"], "failure": response.get("error", response)})
                note = "  FAILED"
            print(f"  {out_name:18} {method:26} {item['id'][ident]}{note}")
        # One line, so `tools-write-lf.test.ts` can see both pinned arguments:
        # it reads physical lines, and a wrapped call hides them from it.
        body = json.dumps({"entries": entries}, indent=2)
        (out / out_name).write_text(body, encoding="utf-8", newline="\n")
    return failures


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__.strip().splitlines()[0], file=sys.stderr)
        print(f"usage: {sys.argv[0]} <output-directory>", file=sys.stderr)
        return 2

    key = os.environ.get("BATTLEGRID_API_KEY")
    if not key:
        print("BATTLEGRID_API_KEY is not set.", file=sys.stderr)
        return 2

    out = Path(sys.argv[1])
    out.mkdir(parents=True, exist_ok=True)

    for name, method, params in DUMPS:
        response = rpc(key, method, params)
        if "result" not in response:
            # A refusal is written nowhere. The generator reads ["result"] and
            # would raise on a file holding an error envelope — but it would
            # raise on the *next* run too, having overwritten a good dump with
            # a bad one. Fail here, with what the server said.
            print(f"{method}: no result — {json.dumps(response)[:200]}", file=sys.stderr)
            return 1
        (out / name).write_text(json.dumps(response, indent=2), encoding="utf-8", newline="\n")
        result = response["result"]
        size = (
            len(result.get("tools") or result.get("prompts") or result.get("resources")
                or result.get("resourceTemplates") or [])
            if isinstance(result, dict)
            else 0
        )
        print(f"  {name:18} {method:26} {size if size else ''}".rstrip())

    body_failures = harvest_bodies(key, out)
    if body_failures:
        print(f"{body_failures} prose bodies refused — recorded as named failures", file=sys.stderr)

    info = json.loads((out / "init.txt").read_text(encoding="utf-8"))["result"]
    server = info.get("serverInfo") or {}
    print(f"\ncaptured {server.get('name', '?')} v{server.get('version', '?')} to {out}/")
    # No `>` redirect here, deliberately. The generator *writes* both artifacts
    # into the dump directory and prints a coverage summary to stdout — so
    # `… > docs/BATTLEGRID_MCP_REFERENCE.md`, which this line used to suggest,
    # would replace the reference with five lines of coverage counts.
    print(f"next: python3 tools/generate_mcp_reference.py {out}")
    print(f"      cp {out}/mcp-capabilities.json docs/battlegrid-mcp-capabilities.json")
    print(f"      cp {out}/mcp-reference.md      docs/BATTLEGRID_MCP_REFERENCE.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
