"""Dump BattleGrid's raw discovery responses, for `generate_mcp_reference.py`.

The gap this closes: CLAUDE.md says one tool regenerates both the surface record
and the reference, and two do. `probe_mcp_surface.py` writes the record;
`generate_mcp_reference.py` reads a *directory of raw JSON-RPC dumps* that
nothing in the repository produced. So the reference could only ever be
regenerated by whoever had those files, and it sat at v17.2.0 while the record
moved to v18.2.0 (#186).

This is the missing step, and deliberately nothing more. It captures and writes;
it does not interpret. The five files are the server's own envelopes, unedited,
because the generator reads `["result"]` out of each and any shaping here would
be this tool deciding what the reference is allowed to say.

The protocol handling is imported from the probe rather than repeated. Two
implementations of "speak MCP and unwrap an SSE frame" would drift, and the
probe's is the one that has been run against a live server through six major
versions.

    BATTLEGRID_API_KEY=bg_live_… python3 tools/capture_mcp_dump.py build_log/dump
    python3 tools/generate_mcp_reference.py build_log/dump > docs/BATTLEGRID_MCP_REFERENCE.md

Reconnaissance only. Every call is a list or an initialize; no tool is invoked,
so nothing here can write to an account.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from probe_mcp_surface import rpc  # noqa: E402

# What the generator opens, and the method that fills each. Kept as data so the
# two stay visibly paired — a file the generator reads and nothing writes is the
# defect this exists to fix, and the next one would look identical.
DUMPS: list[tuple[str, str, dict]] = [
    (
        "init.txt",
        "initialize",
        {
            "protocolVersion": "2025-06-18",
            "capabilities": {},
            "clientInfo": {"name": "grid-commander-capture", "version": "1.0.0"},
        },
    ),
    ("tools.json", "tools/list", {}),
    ("prompts.json", "prompts/list", {}),
    ("resources.json", "resources/list", {}),
    ("restemplates.json", "resources/templates/list", {}),
]


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__.strip().splitlines()[0], file=sys.stderr)
        print(f"usage: {sys.argv[0]} <output-directory>", file=sys.stderr)
        return 2

    key = os.environ.get("BATTLEGRID_API_KEY")
    if not key:
        print("BATTLEGRID_API_KEY is not set.", file=sys.stderr)
        return 2

    out = Path(sys.argv[1])
    out.mkdir(parents=True, exist_ok=True)

    for name, method, params in DUMPS:
        response = rpc(key, method, params)
        if "result" not in response:
            # A refusal is written nowhere. The generator reads ["result"] and
            # would raise on a file holding an error envelope — but it would
            # raise on the *next* run too, having overwritten a good dump with
            # a bad one. Fail here, with what the server said.
            print(f"{method}: no result — {json.dumps(response)[:200]}", file=sys.stderr)
            return 1
        (out / name).write_text(json.dumps(response, indent=2), encoding="utf-8", newline="\n")
        result = response["result"]
        size = (
            len(result.get("tools") or result.get("prompts") or result.get("resources")
                or result.get("resourceTemplates") or [])
            if isinstance(result, dict)
            else 0
        )
        print(f"  {name:18} {method:26} {size if size else ''}".rstrip())

    info = json.loads((out / "init.txt").read_text(encoding="utf-8"))["result"]
    server = info.get("serverInfo") or {}
    print(f"\ncaptured {server.get('name', '?')} v{server.get('version', '?')} to {out}/")
    print("next: python3 tools/generate_mcp_reference.py "
          f"{out} > docs/BATTLEGRID_MCP_REFERENCE.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
