#!/usr/bin/env node
/**
 * openspec/design/system.json -> app/tokens.css + tailwind.theme.json
 *
 * DT-0001. The design system is the single source of truth for every value in
 * the UI; this script is what makes that true rather than aspirational. Editing
 * a colour in tailwind.theme.json by hand is pointless — the next run
 * overwrites it — which is the property the ticket asks for.
 *
 * Colours become CSS custom properties rather than literals so that light and
 * dark are one declaration each instead of a `dark:` variant on every element.
 * A role missing from the dark set is an error, not a fallback: inheriting a
 * light value into dark is how contrast failures ship.
 *
 * Run: node tools/generate-theme.mjs   (also runs via `pnpm predev`/`prebuild`)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const system = JSON.parse(readFileSync(join(root, 'openspec/design/system.json'), 'utf8'));

if (system.status !== 'designed') {
  console.warn(`warning: design system status is '${system.status}', not 'designed'`);
}

const colors = system.tokens.color;
const dark = colors.dark ?? {};

/** Flatten { accent: { default: '#..' } } -> [['accent-default', '#..']]. */
function flatten(obj, prefix = []) {
  const out = [];
  for (const [key, value] of Object.entries(obj)) {
    if (key === 'dark') continue;
    const path = [...prefix, key];
    if (value && typeof value === 'object') out.push(...flatten(value, path));
    else out.push([path.join('-'), value]);
  }
  return out;
}

const light = flatten(colors);
const darkPairs = new Map(flatten(dark));

/**
 * Non-colour dimension tokens. DT-0003: `size.control.min` is the 44px
 * tap-target floor the principles always stated and the space scale skips
 * (32px, then 48px). Sizes have no dark counterpart — they go in `:root` once.
 */
const sizes = flatten(system.tokens.size ?? {});

const missing = light.map(([name]) => name).filter((name) => !darkPairs.has(name));
if (missing.length > 0) {
  console.error(`error: no dark value for: ${missing.join(', ')}`);
  console.error('every colour role needs a dark counterpart — inheriting a light value into dark ships a contrast failure');
  process.exit(1);
}

const varName = (name) => `--gc-${name}`;

const css = `/* GENERATED by tools/generate-theme.mjs from openspec/design/system.json.
   Do not edit. Change the design system and re-run. */

:root {
${light.map(([n, v]) => `  ${varName(n)}: ${v};`).join('\n')}
${sizes.map(([n, v]) => `  ${varName(`size-${n}`)}: ${v};`).join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root {
${light.map(([n]) => `    ${varName(n)}: ${darkPairs.get(n)};`).join('\n')}
  }
}

@media (prefers-reduced-motion: reduce) {
  /* Motion is decoration and must never gate feedback. */
  *, *::before, *::after {
    animation-duration: ${system.tokens.motion.duration.instant} !important;
    transition-duration: ${system.tokens.motion.duration.instant} !important;
    scroll-behavior: auto !important;
  }
}
`;

/**
 * Tailwind gets `extend`, never a replacement theme. The 28 components already
 * written use stock utilities (`p-3`, `text-sm`, `max-w-2xl`); replacing the
 * theme would break every one of them, and this ticket edits no component.
 */
const theme = {
  extend: {
    colors: Object.fromEntries(
      light.map(([n]) => [n, `var(${varName(n)})`]),
    ),
    fontFamily: {
      sans: system.tokens.type.family.sans.split(',').map((s) => s.trim()),
      mono: system.tokens.type.family.mono.split(',').map((s) => s.trim()),
    },
    borderRadius: Object.fromEntries(
      Object.entries(system.tokens.radius).map(([k, v]) => [`gc-${k}`, v]),
    ),
    boxShadow: Object.fromEntries(
      Object.entries(system.tokens.shadow).map(([k, v]) => [`gc-${k}`, v]),
    ),
    transitionDuration: Object.fromEntries(
      Object.entries(system.tokens.motion.duration).map(([k, v]) => [k, v]),
    ),
    // One explicit mapping while the size group has one token; generalise when
    // it grows a second. `min-h-control` is the utility DT-0003 names.
    minHeight: {
      control: `var(${varName('size-control-min')})`,
    },
    transitionTimingFunction: system.tokens.motion.easing,
    screens: Object.fromEntries(
      Object.entries(system.tokens.breakpoint)
        .filter(([, v]) => v !== '0')
        .map(([k, v]) => [k, v]),
    ),
  },
};

writeFileSync(join(root, 'app/tokens.css'), css);
writeFileSync(join(root, 'tailwind.theme.json'), JSON.stringify(theme, null, 2) + '\n');
console.log(`generated app/tokens.css and tailwind.theme.json — ${light.length} colour roles`);
